import type {NextPage} from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {Animal} from '../models/local/mobx.example'
import MobxReaction from '../components/mobx'
import UserCreation from '../components/cognito'
import DataList from '../components/datastore'
import Messaging from '../components/messaging'
import UserAnalytics from '../components/pinpoint'
import ContactConfirmation from '../components/confirmContact'
import DeleteUser from '../components/delete-user'
import CreateUser from '../components/create-user'
import UploadServiceDefinitions from '../components/uploadServiceDefinitions'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>My Prototypes</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to my Prototypes!</h1>
        <div className={styles.grid}>
          <UploadServiceDefinitions />
          <DeleteUser />
          <CreateUser />
          <UserCreation />
          {/* Mobx */}
          <MobxReaction animal={new Animal('girafe')} />
          {/* Data List */}
          <DataList />
          <Messaging />
          <UserAnalytics />
          <ContactConfirmation />
        </div>
      </main>
    </div>
  )
}

export default Home
