import type {NextPage} from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {Animal} from "../models/mobx.example";
import MobxReaction from "../components/mobx";
import UserCreation from "../components/cognito";
import DataList from '../components/datastore';

const Home: NextPage = () => {

  return (
    <div className={styles.container}>
      <Head>
        <title>My Prototypes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to my Prototypes!
        </h1>
        <div className={styles.grid}>
          {/* Mobx */}
          <MobxReaction animal={new Animal('girafe')} />
          {/* Cognito user */}
          <UserCreation />
          {/* Data List */}
          <DataList />
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
