/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'ap-south-1',
  aws_appsync_graphqlEndpoint:
    'https://3g7rbbxmkvhnhprbuv57egicdy.appsync-api.ap-south-1.amazonaws.com/graphql',
  aws_appsync_region: 'ap-south-1',
  aws_appsync_authenticationType: 'API_KEY',
  aws_appsync_apiKey: 'da2-fbcmb72kbfeu5muniv4roe6jhe',
  aws_cloud_logic_custom: [
    {
      name: 'AdminQueries',
      endpoint:
        'https://rc9g7n08yi.execute-api.ap-south-1.amazonaws.com/sampledev',
      region: 'ap-south-1',
    },
  ],
  aws_cognito_identity_pool_id:
    'ap-south-1:6f9eb09d-19dc-42e6-9f17-247f4f94f495',
  aws_cognito_region: 'ap-south-1',
  aws_user_pools_id: 'ap-south-1_kUoVSVvao',
  aws_user_pools_web_client_id: '40uc0u1i15mag7h4e8q757q89o',
  oauth: {},
  aws_cognito_username_attributes: [],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: ['EMAIL', 'PHONE_NUMBER'],
  aws_cognito_mfa_configuration: 'OFF',
  aws_cognito_mfa_types: ['SMS'],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ['EMAIL'],
  aws_user_files_s3_bucket: 'cko-bucket231248-sampledev',
  aws_user_files_s3_bucket_region: 'ap-south-1',
}

export default awsmobile
