/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
import * as awsmobileprod from './aws-exports.prod'
import * as awsmobiledev from './aws-exports.dev'
import * as awsmobilesampledev from './aws-exports.sampledev'
import * as awsmobiletest from './aws-exports.test'
let awsmobile

switch (process.env.AWS_ENV) {
  case 'PROD':
    awsmobile = awsmobileprod.default
    break
  case 'DEV':
    awsmobile = awsmobiledev.default
    break
  case 'SAMPLEDEV':
    awsmobile = awsmobilesampledev.default
    break
  case 'TEST':
    awsmobile = awsmobiletest.default
    break
  default:
    awsmobile = awsmobiledev.default
    break
}

export default awsmobile
