/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
import * as awsmobileprod from "./aws-exports.prod";
import * as awsmobiledev from "./aws-exports.dev";
import * as awsmobilesampledev from "./aws-exports.sampledev";

// const awsmobileold = {
//   aws_project_region: 'ap-south-1',
//   aws_appsync_graphqlEndpoint:
//     'https://y7nk7ngtvnaevezr73o4lroszi.appsync-api.ap-south-1.amazonaws.com/graphql',
//   aws_appsync_region: 'ap-south-1',
//   aws_appsync_authenticationType: 'API_KEY',
//   aws_appsync_apiKey: 'da2-wy52rs4lm5dk5oj62m7z57e6ry',
//   aws_cognito_identity_pool_id:
//     'ap-south-1:0e702711-96c4-4959-98b9-81324bac6d10',
//   aws_cognito_region: 'ap-south-1',
//   aws_user_pools_id: 'ap-south-1_DWbOlqdnt',
//   aws_user_pools_web_client_id: '338gu0ota68vgffrvofmno9l1f',
//   oauth: {},
//   aws_user_files_s3_bucket: 'cko-bucket160953-develop',
//   aws_user_files_s3_bucket_region: 'ap-south-1',
//   appInstanceArn:
//     'arn:aws:chime:us-east-1:097212506913:app-instance/3ffa8a88-5227-41e1-a582-ca5378a43799',
//   chime_region: 'us-east-1', // Only supported region for Amazon Chime SDK Messaging as of this writing
// }
// const awsmobileold2 = {
//   aws_project_region: 'ap-south-1',
//   aws_appsync_graphqlEndpoint:
//     'https://y7nk7ngtvnaevezr73o4lroszi.appsync-api.ap-south-1.amazonaws.com/graphql',
//   aws_appsync_region: 'ap-south-1',
//   aws_appsync_authenticationType: 'API_KEY',
//   aws_appsync_apiKey: 'da2-wy52rs4lm5dk5oj62m7z57e6ry',
//   aws_cognito_identity_pool_id:
//     'ap-south-1:0e702711-96c4-4959-98b9-81324bac6d10',
//   aws_cognito_region: 'ap-south-1',
//   aws_user_pools_id: 'ap-south-1_DWbOlqdnt',
//   aws_user_pools_web_client_id: '338gu0ota68vgffrvofmno9l1f',
//   oauth: {},
//   aws_cognito_username_attributes: [],
//   aws_cognito_social_providers: [],
//   aws_cognito_signup_attributes: ['EMAIL', 'PHONE_NUMBER'],
//   aws_cognito_mfa_configuration: 'OFF',
//   aws_cognito_mfa_types: ['SMS'],
//   aws_cognito_password_protection_settings: {
//     passwordPolicyMinLength: 8,
//     passwordPolicyCharacters: [],
//   },
//   aws_cognito_verification_mechanisms: ['EMAIL'],
//   aws_user_files_s3_bucket: 'cko-bucket160953-develop',
//   aws_user_files_s3_bucket_region: 'ap-south-1',
//   aws_mobile_analytics_app_id: '962d6b673d2e4a9a9b6487c1eff9cf7a',
//   aws_mobile_analytics_app_region: 'us-west-2',
//   appInstanceArn:
//     'arn:aws:chime:us-east-1:097212506913:app-instance/3ffa8a88-5227-41e1-a582-ca5378a43799',
//   chime_region: 'us-east-1', // Only supported region for Amazon Chime SDK Messaging as of this writing
// }

// const awsmobileProd = {
//   aws_project_region: 'ap-south-1',
//   aws_appsync_graphqlEndpoint:
//     'https://g37alxxobfgilgp7jhbfeedv2i.appsync-api.ap-south-1.amazonaws.com/graphql',
//   aws_appsync_region: 'ap-south-1',
//   aws_appsync_authenticationType: 'API_KEY',
//   aws_appsync_apiKey: 'da2-ittwfuibfza7dlawnbdcz6djeu',
//   aws_cloud_logic_custom: [
//     {
//       name: 'AdminQueries',
//       endpoint: 'https://pxte82v9q5.execute-api.ap-south-1.amazonaws.com/prod',
//       region: 'ap-south-1',
//     },
//   ],
//   aws_cognito_identity_pool_id:
//     'ap-south-1:f23d95b5-956c-4b57-b1a8-af24685190b3',
//   aws_cognito_region: 'ap-south-1',
//   aws_user_pools_id: 'ap-south-1_DYzettZ38',
//   aws_user_pools_web_client_id: '783pfige3radgoao5860kgq8uh',
//   oauth: {},
//   aws_cognito_username_attributes: ['EMAIL', 'PHONE_NUMBER'],
//   aws_cognito_social_providers: [],
//   aws_cognito_signup_attributes: ['EMAIL', 'PHONE_NUMBER'],
//   aws_cognito_mfa_configuration: 'OPTIONAL',
//   aws_cognito_mfa_types: ['SMS'],
//   aws_cognito_password_protection_settings: {
//     passwordPolicyMinLength: '6',
//     passwordPolicyCharacters: [],
//   },
//   aws_cognito_verification_mechanisms: ['EMAIL'],
//   aws_user_files_s3_bucket: 'cko-bucket72714-prod',
//   aws_user_files_s3_bucket_region: 'ap-south-1',
//   appInstanceArn:
//     'arn:aws:chime:us-east-1:097212506913:app-instance/3ffa8a88-5227-41e1-a582-ca5378a43799',
//   chime_region: 'us-east-1', // Only supported region for Amazon Chime SDK Messaging as of this writing
//   aws_mobile_analytics_app_id: 'a150facef4fd488191e28e7c7089f702',
//   aws_mobile_analytics_app_region: 'ap-south-1',
// }

// const awsmobileDev = {
//   aws_project_region: 'ap-south-1',
//   aws_appsync_graphqlEndpoint:
//     'https://hjoul43oebgr3nxkzgvrlvlwfq.appsync-api.ap-south-1.amazonaws.com/graphql',
//   aws_appsync_region: 'ap-south-1',
//   aws_appsync_authenticationType: 'API_KEY',
//   aws_appsync_apiKey: 'da2-2focctqtebfchj7vy6mzqcyega',
//   aws_cloud_logic_custom: [
//     {
//       name: 'AdminQueries',
//       endpoint: 'https://pxte82v9q5.execute-api.ap-south-1.amazonaws.com/prod',
//       region: 'ap-south-1',
//     },
//   ],
//   aws_cognito_identity_pool_id:
//     'ap-south-1:f4565cd9-0e23-405c-9497-69aa1af57077',
//   aws_cognito_region: 'ap-south-1',
//   aws_user_pools_id: 'ap-south-1_08xei5r43',
//   aws_user_pools_web_client_id: '3johprl9hjr7970fcbj0t12ktv',
//   oauth: {},
//   aws_cognito_username_attributes: [],
//   aws_cognito_social_providers: [],
//   aws_cognito_signup_attributes: ['EMAIL', 'PHONE_NUMBER'],
//   aws_cognito_mfa_configuration: 'OPTIONAL',
//   aws_cognito_mfa_types: ['SMS', 'TOTP'],
//   aws_cognito_password_protection_settings: {
//     passwordPolicyMinLength: 8,
//     passwordPolicyCharacters: [
//       'REQUIRES_LOWERCASE',
//       'REQUIRES_UPPERCASE',
//       'REQUIRES_NUMBERS',
//       'REQUIRES_SYMBOLS',
//     ],
//   },
//   aws_cognito_verification_mechanisms: ['EMAIL', 'PHONE_NUMBER'],
//   aws_user_files_s3_bucket: 'cko-bucket153613-dev',
//   aws_user_files_s3_bucket_region: 'ap-south-1',
//   appInstanceArn:
//     'arn:aws:chime:us-east-1:097212506913:app-instance/3ffa8a88-5227-41e1-a582-ca5378a43799',
//   chime_region: 'us-east-1', // Only supported region for Amazon Chime SDK Messaging as of this writing
//   aws_mobile_analytics_app_id: 'a150facef4fd488191e28e7c7089f702',
//   aws_mobile_analytics_app_region: 'ap-south-1',
// }

const awsmobile = awsmobiledev.default
// const awsmobile = awsmobilesprod.default
// const awsmobile = awsmobilesampledev.default
export default awsmobile

