/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobileold = {
  aws_project_region: 'ap-south-1',
  aws_appsync_graphqlEndpoint:
    'https://y7nk7ngtvnaevezr73o4lroszi.appsync-api.ap-south-1.amazonaws.com/graphql',
  aws_appsync_region: 'ap-south-1',
  aws_appsync_authenticationType: 'API_KEY',
  aws_appsync_apiKey: 'da2-wy52rs4lm5dk5oj62m7z57e6ry',
  aws_cognito_identity_pool_id:
    'ap-south-1:0e702711-96c4-4959-98b9-81324bac6d10',
  aws_cognito_region: 'ap-south-1',
  aws_user_pools_id: 'ap-south-1_DWbOlqdnt',
  aws_user_pools_web_client_id: '338gu0ota68vgffrvofmno9l1f',
  oauth: {},
  aws_user_files_s3_bucket: 'cko-bucket160953-develop',
  aws_user_files_s3_bucket_region: 'ap-south-1',
  appInstanceArn:
    'arn:aws:chime:us-east-1:097212506913:app-instance/3ffa8a88-5227-41e1-a582-ca5378a43799',
  chime_region: 'us-east-1', // Only supported region for Amazon Chime SDK Messaging as of this writing
}
const awsmobileold2 = {
  aws_project_region: 'ap-south-1',
  aws_appsync_graphqlEndpoint:
    'https://y7nk7ngtvnaevezr73o4lroszi.appsync-api.ap-south-1.amazonaws.com/graphql',
  aws_appsync_region: 'ap-south-1',
  aws_appsync_authenticationType: 'API_KEY',
  aws_appsync_apiKey: 'da2-wy52rs4lm5dk5oj62m7z57e6ry',
  aws_cognito_identity_pool_id:
    'ap-south-1:0e702711-96c4-4959-98b9-81324bac6d10',
  aws_cognito_region: 'ap-south-1',
  aws_user_pools_id: 'ap-south-1_DWbOlqdnt',
  aws_user_pools_web_client_id: '338gu0ota68vgffrvofmno9l1f',
  oauth: {},
  aws_cognito_username_attributes: [],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: ['EMAIL', 'PHONE_NUMBER'],
  aws_cognito_mfa_configuration: 'OFF',
  aws_cognito_mfa_types: ['SMS'],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ['EMAIL'],
  aws_user_files_s3_bucket: 'cko-bucket160953-develop',
  aws_user_files_s3_bucket_region: 'ap-south-1',
  aws_mobile_analytics_app_id: '962d6b673d2e4a9a9b6487c1eff9cf7a',
  aws_mobile_analytics_app_region: 'us-west-2',
  appInstanceArn:
    'arn:aws:chime:us-east-1:097212506913:app-instance/3ffa8a88-5227-41e1-a582-ca5378a43799',
  chime_region: 'us-east-1', // Only supported region for Amazon Chime SDK Messaging as of this writing
}

const awsmobile = {
  aws_project_region: 'ap-south-1',
  aws_appsync_graphqlEndpoint:
    'https://3g7rbbxmkvhnhprbuv57egicdy.appsync-api.ap-south-1.amazonaws.com/graphql',
  aws_appsync_region: 'ap-south-1',
  aws_appsync_authenticationType: 'API_KEY',
  aws_appsync_apiKey: 'da2-fbcmb72kbfeu5muniv4roe6jhe',
  aws_cloud_logic_custom: [
    {
      name: 'AdminQueries',
      endpoint:
        'https://rc9g7n08yi.execute-api.ap-south-1.amazonaws.com/sampledev',
      region: 'ap-south-1',
    },
  ],
  aws_cognito_identity_pool_id:
    'ap-south-1:6f9eb09d-19dc-42e6-9f17-247f4f94f495',
  aws_cognito_region: 'ap-south-1',
  aws_user_pools_id: 'ap-south-1_kUoVSVvao',
  aws_user_pools_web_client_id: '40uc0u1i15mag7h4e8q757q89o',
  oauth: {},
  aws_cognito_username_attributes: [],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: ['EMAIL', 'PHONE_NUMBER'],
  aws_cognito_mfa_configuration: 'OFF',
  aws_cognito_mfa_types: ['SMS'],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ['EMAIL'],
  aws_user_files_s3_bucket: 'cko-bucket231248-sampledev',
  aws_user_files_s3_bucket_region: 'ap-south-1',
  appInstanceArn:
    'arn:aws:chime:us-east-1:097212506913:app-instance/3ffa8a88-5227-41e1-a582-ca5378a43799',
  chime_region: 'us-east-1', // Only supported region for Amazon Chime SDK Messaging as of this writing
  aws_mobile_analytics_app_id: 'a150facef4fd488191e28e7c7089f702',
  aws_mobile_analytics_app_region: 'ap-south-1',
}
export default awsmobile
