/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'ap-south-1',
  aws_appsync_graphqlEndpoint:
    'https://g37alxxobfgilgp7jhbfeedv2i.appsync-api.ap-south-1.amazonaws.com/graphql',
  aws_appsync_region: 'ap-south-1',
  aws_appsync_authenticationType: 'API_KEY',
  aws_appsync_apiKey: 'da2-ittwfuibfza7dlawnbdcz6djeu',
  aws_cloud_logic_custom: [
    {
      name: 'AdminQueries',
      endpoint: 'https://pxte82v9q5.execute-api.ap-south-1.amazonaws.com/prod',
      region: 'ap-south-1',
    },
  ],
  aws_cognito_identity_pool_id:
    'ap-south-1:f23d95b5-956c-4b57-b1a8-af24685190b3',
  aws_cognito_region: 'ap-south-1',
  aws_user_pools_id: 'ap-south-1_DYzettZ38',
  aws_user_pools_web_client_id: '783pfige3radgoao5860kgq8uh',
  oauth: {},
  aws_cognito_username_attributes: ['EMAIL', 'PHONE_NUMBER'],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: ['EMAIL', 'PHONE_NUMBER'],
  aws_cognito_mfa_configuration: 'OPTIONAL',
  aws_cognito_mfa_types: ['SMS'],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: '6',
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ['EMAIL'],
  aws_user_files_s3_bucket: 'cko-bucket72714-prod',
  aws_user_files_s3_bucket_region: 'ap-south-1',
}

export default awsmobile
