/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'ap-south-1',
  aws_appsync_graphqlEndpoint:
    'https://hjoul43oebgr3nxkzgvrlvlwfq.appsync-api.ap-south-1.amazonaws.com/graphql',
  aws_appsync_region: 'ap-south-1',
  aws_appsync_authenticationType: 'API_KEY',
  aws_appsync_apiKey: 'da2-2focctqtebfchj7vy6mzqcyega',
  aws_cognito_identity_pool_id:
    'ap-south-1:f4565cd9-0e23-405c-9497-69aa1af57077',
  aws_cognito_region: 'ap-south-1',
  aws_user_pools_id: 'ap-south-1_08xei5r43',
  aws_user_pools_web_client_id: '3johprl9hjr7970fcbj0t12ktv',
  oauth: {},
  aws_cognito_username_attributes: [],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: ['EMAIL', 'PHONE_NUMBER'],
  aws_cognito_mfa_configuration: 'OPTIONAL',
  aws_cognito_mfa_types: ['SMS', 'TOTP'],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [
      'REQUIRES_LOWERCASE',
      'REQUIRES_UPPERCASE',
      'REQUIRES_NUMBERS',
      'REQUIRES_SYMBOLS',
    ],
  },
  aws_cognito_verification_mechanisms: ['EMAIL', 'PHONE_NUMBER'],
  aws_user_files_s3_bucket: 'cko-bucket153613-dev',
  aws_user_files_s3_bucket_region: 'ap-south-1',
}

export default awsmobile
